// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzuKwHCveq-nQBoT4kz-MzMr_LXQnBoo',
    appId: '1:129948273465:web:ef5d73b3a6b6de94c076e8',
    messagingSenderId: '129948273465',
    projectId: 'kigali-services-director-ffaf1',
    authDomain: 'kigali-services-director-ffaf1.firebaseapp.com',
    databaseURL: 'https://kigali-services-director-ffaf1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kigali-services-director-ffaf1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbPquil4D82nTDT4s63BTZqGkX2HXGKk4',
    appId: '1:129948273465:android:ccbbdaf73d66c9b8c076e8',
    messagingSenderId: '129948273465',
    projectId: 'kigali-services-director-ffaf1',
    databaseURL: 'https://kigali-services-director-ffaf1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kigali-services-director-ffaf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ32DlZ1BWjH1FV0Afvt7XHeK5V2NmaHA',
    appId: '1:129948273465:ios:e4e5eb9c2ce43826c076e8',
    messagingSenderId: '129948273465',
    projectId: 'kigali-services-director-ffaf1',
    databaseURL: 'https://kigali-services-director-ffaf1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kigali-services-director-ffaf1.firebasestorage.app',
    iosBundleId: 'com.example.visitKigaliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ32DlZ1BWjH1FV0Afvt7XHeK5V2NmaHA',
    appId: '1:129948273465:ios:e4e5eb9c2ce43826c076e8',
    messagingSenderId: '129948273465',
    projectId: 'kigali-services-director-ffaf1',
    databaseURL: 'https://kigali-services-director-ffaf1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kigali-services-director-ffaf1.firebasestorage.app',
    iosBundleId: 'com.example.visitKigaliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSzuKwHCveq-nQBoT4kz-MzMr_LXQnBoo',
    appId: '1:129948273465:web:4d28fe9a5fb8a6dac076e8',
    messagingSenderId: '129948273465',
    projectId: 'kigali-services-director-ffaf1',
    authDomain: 'kigali-services-director-ffaf1.firebaseapp.com',
    databaseURL: 'https://kigali-services-director-ffaf1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kigali-services-director-ffaf1.firebasestorage.app',
  );
}
